/**
 * Autogenerated Types for the Interactive ESL Routine Lab
 */

export interface RoutineActivity {
  id: string;
  phrase: string; // e.g., "brush my teeth"
  startTime: number; // 0 to 23 Hours
  duration: number; // in hours, usually 1 or greater
  category: 'health' | 'leisure' | 'work' | 'study' | 'sleep' | 'other';
}

export interface UserStats {
  vocabCompleted: boolean;
  vocabGapScore: number; // max 8
  vocabAnswersState: Record<number, string>; // questionIdx -> answered word

  dialogueCompleted: boolean;
  dialogueScore: number; // max 4 (gap fills)
  dialogueAnswersState: Record<string, string>;

  grammarCompleted: boolean;
  grammarScrambleScore: number; // max 4
  grammarAnswersState: Record<number, string[]>; // questionIdx -> word array order

  errorsCompleted: boolean;
  errorsScore: number; // max 3
  errorsAnswersState: Record<number, string>; // completed corrected sentence

  activeStudyTime: number; // in seconds
  stars: number; // running total
  avatar: string;
  userName: string;
}

export interface VocabularyItem {
  phrase: string;
  example: string;
  translationExplain: string;
  category: 'health' | 'leisure' | 'work' | 'study' | 'sleep' | 'other';
  imagePlaceholderColor: string;
}

export interface DialogueNode {
  id: string;
  character: 'Rohan' | 'Maya';
  text: string;
  translationExplain: string;
  timeOfDay: 'morning' | 'afternoon' | 'night';
}

export interface ScrambledSentence {
  id: number;
  scrambledWords: string[];
  correctSentence: string;
  hint: string;
}

export interface ErrorSentence {
  id: number;
  incorrect: string;
  correct: string;
  explanation: string;
  hint: string;
}
